#
# Swaybar configuration
#
# The listed components will be rendered according to their order
# value from left to right in increasing order.
#
#
# Interval
#
# The interval value must be specified as a positive integer value
# followed by a unit of time:
#
#     (s): seconds
#     (ms): milliseconds 1e3
#     (us): microseconds 1e6
#     (ns): nanoseconds  1e9
#
# For fractional units of time, use a more fine-grained unit:
#
#     "500ms" - equivalent to 0.5 seconds
#
# If not specified, the default value of one second will be used.
#
#
# Date
#
# The date format can be either a predefined format or a custom one.
#
# Example Layouts:
#
#    Layout      = "01/02 03:04:05PM '06 -0700"
#    ANSIC       = "Mon Jan _2 15:04:05 2006"
#    UnixDate    = "Mon Jan _2 15:04:05 MST 2006"
#    RubyDate    = "Mon Jan 02 15:04:05 -0700 2006"
#    RFC822      = "02 Jan 06 15:04 MST"
#    RFC822Z     = "02 Jan 06 15:04 -0700"
#    RFC850      = "Monday, 02-Jan-06 15:04:05 MST"
#    RFC1123     = "Mon, 02 Jan 2006 15:04:05 MST"
#    RFC1123Z    = "Mon, 02 Jan 2006 15:04:05 -0700"
#    RFC3339     = "2006-01-02T15:04:05Z07:00"
#    RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
#    Kitchen     = "3:04PM"
#    Stamp       = "Jan _2 15:04:05"
#    StampMilli  = "Jan _2 15:04:05.000"
#    StampMicro  = "Jan _2 15:04:05.000000"
#    StampNano   = "Jan _2 15:04:05.000000000"
#    DateTime    = "2006-01-02 15:04:05"
#    DateOnly    = "2006-01-02"
#    TimeOnly    = "15:04:05"
#
network:
  interval: "1s"
  order: 0
  device: "enp6s0"

cpuutil:
  interval: "1s"
  order: 1

cputemp:
  interval: "1s"
  order: 2
  name: "coretemp"
  label: "package"

gpu:
  interval: "1s"
  order: 3
  name: "amdgpu"
  label: "edge"

date:
  interval: "1s"
  order: 4
  format: "01/02/2006 15:04:05"
